name: Deploy
on:
  push:
    branches: [ "main" ]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Unit Tests
        run: mvn clean package

      - name: Rename the artifact
        run: cp target/github-spring-boot github-spring-boot-${{ github.sha }}.jar

      - name: Save the artifact
        uses: actions/upload-artifact@main
        with:
          name: github-spring-boot
          path: github-spring-boot-${{ github.sha }}.jar

  fake-deploy:
    runs-on: ubuntu-latest
    needs: run-unit-tests
    steps:
      - name: Get the artifact
        uses: actions/download-artifact@main
        with:
          name: github-spring-boot

      - name: Fake Deploy
        run: ls github-spring-boot*.jar
